/**
* User account and session management
* Provides HTTP endpoints to manage User Accounts and User Sessions.
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.accountservice.sdk.models

import com.equisoft.accountservice.sdk.models.LocalizedString

import com.squareup.moshi.Json

/**
 * A request to create a new organization
 * @param name 
 * @param equisoftConnectProfiles 
 * @param equisoftPlanProfiles 
 * @param parentUuid 
 */

data class CreateOrganizationPayload (
    @Json(name = "name")
    val name: LocalizedString? = null,
    @Json(name = "equisoftConnectProfiles")
    val equisoftConnectProfiles: kotlin.collections.List<kotlin.String>? = null,
    @Json(name = "equisoftPlanProfiles")
    val equisoftPlanProfiles: kotlin.collections.List<kotlin.String>? = null,
    @Json(name = "parentUuid")
    val parentUuid: kotlin.String? = null
)

