/**
* User account and session management
* Provides HTTP endpoints to manage User Accounts and User Sessions.
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.accountservice.sdk.models


import com.squareup.moshi.Json

/**
 * Parameters needed to impersonanted a user for a user session
 * @param userUuid Globally unique identifier.
 */

data class ImpersonatePayload (
    /* Globally unique identifier. */
    @Json(name = "userUuid")
    val userUuid: kotlin.String? = null
)

