/**
* User account and session management
* Provides HTTP endpoints to manage User Accounts and User Sessions.
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.accountservice.sdk.models


import com.squareup.moshi.Json

/**
 * 
 * @param values 
 * @param defaultLocale 
 */

data class LocalizedString (
    @Json(name = "values")
    val values: kotlin.collections.Map<kotlin.String, kotlin.String>,
    @Json(name = "defaultLocale")
    val defaultLocale: kotlin.String
)

