/**
* User account and session management
* Provides HTTP endpoints to manage User Accounts and User Sessions.
*
* The version of the OpenAPI document: 0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.accountservice.sdk.models

import com.equisoft.accountservice.sdk.models.LocalizedString
import com.equisoft.accountservice.sdk.models.OrganizationPathElement

import com.squareup.moshi.Json

/**
 * 
 * @param uuid 
 * @param name 
 * @param path Path to the root organization, starting from the top level organization
 * @param equisoftConnectProfiles 
 * @param equisoftPlanProfiles 
 * @param createdAt 
 * @param parentUuid 
 * @param modifiedAt 
 */

data class Organization (
    @Json(name = "uuid")
    val uuid: kotlin.String,
    @Json(name = "name")
    val name: LocalizedString,
    /* Path to the root organization, starting from the top level organization */
    @Json(name = "path")
    val path: kotlin.collections.List<OrganizationPathElement>,
    @Json(name = "equisoftConnectProfiles")
    val equisoftConnectProfiles: kotlin.collections.List<kotlin.String>,
    @Json(name = "equisoftPlanProfiles")
    val equisoftPlanProfiles: kotlin.collections.List<kotlin.String>,
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,
    @Json(name = "parentUuid")
    val parentUuid: kotlin.String? = null,
    @Json(name = "modifiedAt")
    val modifiedAt: java.time.OffsetDateTime? = null
)

