/**
* User account and session management
* Provides HTTP endpoints to manage User Accounts and User Sessions.
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.accountservice.sdk.models

import com.equisoft.accountservice.sdk.models.LocalizedString
import com.equisoft.accountservice.sdk.models.UserAccountPermission
import com.equisoft.accountservice.sdk.models.UserAccountRole

import com.squareup.moshi.Json

/**
 * 
 * @param uuid 
 * @param name 
 * @param parents 
 * @param roles 
 * @param permissions 
 */

data class RolesOnOrganization (
    @Json(name = "uuid")
    val uuid: kotlin.String? = null,
    @Json(name = "name")
    val name: LocalizedString? = null,
    @Json(name = "parents")
    val parents: kotlin.collections.List<kotlin.String>? = null,
    @Json(name = "roles")
    val roles: kotlin.collections.List<UserAccountRole>? = null,
    @Json(name = "permissions")
    val permissions: kotlin.collections.List<UserAccountPermission>? = null
)

