/**
* User account and session management
* Provides HTTP endpoints to manage User Accounts and User Sessions.
*
* The version of the OpenAPI document: 0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.accountservice.sdk.models


import com.squareup.moshi.Json

/**
* 
* Values: eQUISOFTCONNECT,eQUISOFTPLAN,eQUISOFTANALYZEFORADVISORS,cPANEL
*/

enum class ServiceName(val value: kotlin.String) {


    @Json(name = "EQUISOFT_CONNECT")
    eQUISOFTCONNECT("EQUISOFT_CONNECT"),

    @Json(name = "EQUISOFT_PLAN")
    eQUISOFTPLAN("EQUISOFT_PLAN"),

    @Json(name = "EQUISOFT_ANALYZE_FOR_ADVISORS")
    eQUISOFTANALYZEFORADVISORS("EQUISOFT_ANALYZE_FOR_ADVISORS"),

    @Json(name = "CPANEL")
    cPANEL("CPANEL");


    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }
}

