/**
* User account and session management
* Provides HTTP endpoints to manage User Accounts and User Sessions.
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.accountservice.sdk.models

import com.equisoft.accountservice.sdk.models.ServiceAccountStatus

import com.squareup.moshi.Json

/**
 * Represents a service account
 * @param uuid 
 * @param name 
 * @param clientId 
 * @param displayName 
 * @param status 
 * @param createdAt 
 * @param modifiedAt 
 */

data class ServiceAccountSchema (
    @Json(name = "uuid")
    val uuid: kotlin.String? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "clientId")
    val clientId: kotlin.String? = null,
    @Json(name = "displayName")
    val displayName: kotlin.String? = null,
    @Json(name = "status")
    val status: ServiceAccountStatus? = null,
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,
    @Json(name = "modifiedAt")
    val modifiedAt: java.time.OffsetDateTime? = null
)

