/**
* User account and session management
* Provides HTTP endpoints to manage User Accounts and User Sessions.
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.accountservice.sdk.models


import com.squareup.moshi.Json

/**
 * A request to update an existing account. All fields are optional
 * @param clientId 
 * @param displayName 
 */

data class ServiceAccountUpdateSchema (
    @Json(name = "clientId")
    val clientId: kotlin.String? = null,
    @Json(name = "displayName")
    val displayName: kotlin.String? = null
)

