/**
* User account and session management
* Provides HTTP endpoints to manage User Accounts and User Sessions.
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.accountservice.sdk.models


import com.squareup.moshi.Json

/**
* States: * `NEW` - Session creation is not finished.  It can't be used by consumer. * `ENABLED` - Session is active and ready. * `SUSPENDED` - Session idle for too long.  User has to reenter credentials to activate it (Not implemented yet). * `EXPIRED` - Session is expired. * `DELETED` - Session exists but is soft-deleted (Not implemented yet). 
* Values: nEW,eNABLED,sUSPENDED,eXPIRED,dELETED
*/

enum class SessionState(val value: kotlin.String) {


    @Json(name = "NEW")
    nEW("NEW"),

    @Json(name = "ENABLED")
    eNABLED("ENABLED"),

    @Json(name = "SUSPENDED")
    sUSPENDED("SUSPENDED"),

    @Json(name = "EXPIRED")
    eXPIRED("EXPIRED"),

    @Json(name = "DELETED")
    dELETED("DELETED");


    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }
}

