/**
* User account and session management
* Provides HTTP endpoints to manage User Accounts and User Sessions.
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.accountservice.sdk.models


import com.squareup.moshi.Json
/**
 * 
 * @param id String that uniquely identify a sso token for a given session.
 * @param value Token value returned as stored. There is no double-encoding.
 */

data class SsoToken (
    /* String that uniquely identify a sso token for a given session. */
    @Json(name = "id")
    val id: kotlin.String? = null,
    /* Token value returned as stored. There is no double-encoding. */
    @Json(name = "value")
    val value: kotlin.String? = null
)

