/**
* User account and session management
* Provides HTTP endpoints to manage User Accounts and User Sessions.
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.accountservice.sdk.models

import com.equisoft.accountservice.sdk.models.ServiceAccess
import com.equisoft.accountservice.sdk.models.UserAgreement
import com.equisoft.accountservice.sdk.models.UserState

import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param uuid 
 * @param displayName 
 * @param email 
 * @param mobilePhone Mobile phone used for sms password reset.
 * @param locale 
 * @param state 
 * @param roles Roles the user is member a member of.
 * @param deletable User deletion is disabled.
 * @param billable User is accounted for billing.
 * @param agreement 
 * @param created 
 * @param services 
 */

data class User (
    @Json(name = "id")
    val id: kotlin.Long? = null,
    @Json(name = "uuid")
    val uuid: kotlin.String? = null,
    @Json(name = "displayName")
    val displayName: kotlin.String? = null,
    @Json(name = "email")
    val email: kotlin.String? = null,
    /* Mobile phone used for sms password reset. */
    @Json(name = "mobilePhone")
    val mobilePhone: kotlin.String? = null,
    @Json(name = "locale")
    val locale: kotlin.String? = null,
    @Json(name = "state")
    val state: UserState? = null,
    /* Roles the user is member a member of. */
    @Json(name = "roles")
    val roles: kotlin.collections.List<kotlin.String>? = null,
    /* User deletion is disabled. */
    @Json(name = "deletable")
    val deletable: kotlin.Boolean? = null,
    /* User is accounted for billing. */
    @Json(name = "billable")
    val billable: kotlin.Boolean? = null,
    @Json(name = "agreement")
    val agreement: UserAgreement? = null,
    @Json(name = "created")
    val created: java.time.OffsetDateTime? = null,
    @Json(name = "services")
    val services: kotlin.collections.List<ServiceAccess>? = null
)

