/**
* User account and session management
* Provides HTTP endpoints to manage User Accounts and User Sessions.
*
* The version of the OpenAPI document: latest
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.accountservice.sdk.models

import com.equisoft.accountservice.sdk.models.LegacyRoleSchema
import com.equisoft.accountservice.sdk.models.RolesOnOrganization

import com.squareup.moshi.Json

/**
 * 
 * @param organizations 
 * @param legacyRoles 
 */

data class UserPermissions (
    @Json(name = "organizations")
    val organizations: kotlin.collections.List<RolesOnOrganization>? = null,
    @Json(name = "legacyRoles")
    val legacyRoles: kotlin.collections.List<LegacyRoleSchema>? = null
)

