/**
* User account and session management
* Provides HTTP endpoints to manage User Accounts and User Sessions.
*
* The version of the OpenAPI document: 0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.equisoft.accountservice.sdk.models


import com.squareup.moshi.Json

/**
* States: * `ACCEPTED` - User agreement and term of use accepted by user. * `REQUESTED` - User has yet to approve user agreements. 
* Values: aCCEPTED,rEQUESTED
*/

enum class UserAgreementState(val value: kotlin.String) {


    @Json(name = "ACCEPTED")
    aCCEPTED("ACCEPTED"),

    @Json(name = "REQUESTED")
    rEQUESTED("REQUESTED");


    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }
}

