name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup asdf-vm
      - name: Cache asdf tooling
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
          restore-keys: ${{ runner.os }}-asdf-
          path: |
            ${ASDF_DIR}/installs
            ${ASDF_DIR}/plugins
      - name: Install required tooling
        uses: asdf-vm/actions/install@v1

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup asdf-vm
      - name: Cache asdf tooling
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
          restore-keys: ${{ runner.os }}-asdf-
          path: |
            ${ASDF_DIR}/installs
            ${ASDF_DIR}/plugins
      - name: Install required tooling
        uses: asdf-vm/actions/install@v1

      - name: Build and Test
        run: ./gradlew assemble test

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup asdf-vm
      - name: Cache asdf tooling
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
          restore-keys: ${{ runner.os }}-asdf-
          path: |
            ${ASDF_DIR}/installs
            ${ASDF_DIR}/plugins
      - name: Install required tooling
        uses: asdf-vm/actions/install@v1

      - name: Publish
        run: ./gradlew -Pgpr.user=clhols -Pgpr.key=${{ secrets.GITHUB_TOKEN }} publish
